from datetime import datetime
from decimal import Decimal
from typing import Optional, List
from datetime import datetime, date

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.pagination import PaginationMetaData
from app.schemas.supplier import SupplierPublic
from app.schemas.user import UserPublic
from app.schemas.base import AutoReadSchema,AutoWriteSchema

class PurchaseOrderBase(BaseModel):
    status: Optional[str] = Field(default=None, validation_alias="Status")
    supplier_id: Optional[int] = Field(default=None, validation_alias="SupplierId")
    purchase_plan_id: Optional[int] = Field(default=None, validation_alias="PurchasePlanId")
    create_user_id: Optional[int] = Field(default=None, validation_alias="CreateUserId")
    total_price: Optional[Decimal] = Field(default=None, validation_alias="TotalPrice")
    
    # Pydantic V2 Config to allow population by field name or alias
    model_config = ConfigDict(populate_by_name=True)

# Create Schema: Fields required to create a new entry
class PurchaseOrderCreate(PurchaseOrderBase):
    # CreateDate might be passed in, or generated by DB. 
    # If passed by client:
    create_date: Optional[datetime] = Field(default=None, validation_alias="CreateDate")

# Read Schema: The full representation including ID and DB-generated fields
class PurchaseOrderRead(PurchaseOrderBase):
    purchase_order_id: int = Field(..., validation_alias="PurchaseOrderId")
    create_date: Optional[datetime] = Field(..., validation_alias="CreateDate")

    # This config is CRITICAL for SQLAlchemy integration
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

class PurchaseOrderPublic(PurchaseOrderBase, AutoReadSchema):
    purchase_order_id: int = Field(..., validation_alias="PurchaseOrderId")
    supplier_name:Optional[str] = Field(default=None, validation_alias='SupplierName')
    model_config = ConfigDict(populate_by_name=True, extra='ignore')
    create_date: Optional[date|datetime] = Field(default=None, validation_alias = "CreateDate")
    create_user_name: Optional[str] = Field(default=None, validation_alias='CreateUserName')
    
class PurchaseOrderMetaDataItem(BaseModel):
    id: int = Field(..., description="ID of related fields")
    label: int = Field(..., description= "Name of meta data instance")

class PurchaseOrderMetaData(BaseModel):
    supplier_types: list

class PurchaseOrderResponse(PaginationMetaData):
    items: list[PurchaseOrderPublic] | None = Field(..., description="List of purchase orders user fetch in a single page")
    suppliers: Optional[list[SupplierPublic]] | None= Field(default=None, description="List of unique suppliers")
    users: Optional[list[UserPublic]] | None= Field(default=None, description="List of unique users", )
    statuses: list | None = Field(default=None, description="List of unique statuses")
    
class PurchaseOrderItemBase(BaseModel):
    purchase_order_item_id: int = Field(..., description="ID of the purchase order")
    product_id: int = Field(..., description="The correspoding product id")
    purchase_order_id: int = Field(...,description="The parent purchase order id")
    quantity: int = Field(..., description="Quantity")
    unit_price:float = Field(..., description="Unit Price we buy from supplier")
    item_description: str = Field(..., description="Special note for purchase order item")
    
class PurchaseOrderItemCreate(PurchaseOrderItemBase):
    """Schema for items coming in the create/update payload"""
    pass

class PurchaseOrderInput(BaseModel):
    """
    The Payload for Creating or Updating a PO.
    Contains the Header info + List of Items.
    """
    supplier_id: int = Field(..., description="Vendor ID")
    is_draft: bool = Field(..., description="True = Save as Draft, False = Confirm & Send")
    purchase_plan_id: Optional[int] = Field(default=None)
    items: List[PurchaseOrderItemCreate] = Field(default=[], description="List of items to save")

    model_config = ConfigDict(populate_by_name=True)
    
class PurchaseOrderItemPublic(PurchaseOrderItemBase, AutoReadSchema):
    purchase_order_item_id: int = Field(..., description="ID of the item")
    purchase_order_id: int = Field(...,description="The parent purchase order id", validation_alias="PurchaseOrderId")
    product_name: Optional[str] = Field(default=None, validation_alias="Product.ProductName")

class PurchaseOrderItemsResponse(BaseModel):
    header: PurchaseOrderPublic = Field(..., description="General data of a purchase order")
    items: list[PurchaseOrderItemPublic] = Field(..., description="Items inside a purchase order")